Feat: TZ13. Каркас приложения для букинга (аренды вещей).
SarychV/java-shareit pull request #1
Opened 2023-10-13 15:08 UTC by SarychV

2023-10-14 05:08 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-10-14 05:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ItemService itemService;
лучше инжектить через конструктор, здесь будет так:
private final ItemService itemService;
и над public class ItemController поставить аннотацию @RequiredArgsConstructor(вроде так называется)

2023-10-14 05:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
> +    Map<Long, Item> items = new HashMap<>();
добавьте модификатор доступа

2023-10-14 05:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    ItemRepository itemRepository;
здесь тоже лучше использовать инжект через конструктор

2023-10-14 05:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public class ItemMapper {
что то я не увидел где бы использовали этот маппер. есть смысл использовать его в контроллере или сервисе

2023-10-14 05:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item createItem(@RequestHeader("X-Sharer-User-Id") @NotNull Integer ownerId,
тут во всех методов надо возвращать ItemDto, раз уж он у вас есть

2023-10-14 05:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>  public class ItemRequest {
не увидел где бы вы его использовали, есть смысл применить его в контроллере в POST/PUT/PATCH методах в качестве RequestBody

2023-10-14 05:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    UserRepository userRepository;
лучше инжект через конструктор

2023-10-14 05:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +public class UserMapper {
удалите пустой класс

2023-10-14 05:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    UserService userService;
лучше инжект через конструктор

2023-10-14 05:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User updateUser(@RequestBody User user, @PathVariable Integer userId) {
public UserDTO updateUser (@RequestBody UserDTO userdto, ..

2023-10-14 05:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User createUser(@RequestBody User user) {
public UserDTO createUser (@Requestbody UserDTO userdto, ..

2023-10-14 05:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User getUser(@PathVariable Integer userId) {
public UserDTO getUser (

2023-10-14 05:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public List<User> getAllUsers() {
public List<UserDTO> getAllUsers (

2023-10-21 09:55 UTC, SarychV commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ItemService itemService;
Исполнил.

2023-10-21 09:57 UTC, SarychV commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
> +    Map<Long, Item> items = new HashMap<>();
Исполнил.

2023-10-21 09:59 UTC, SarychV commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    ItemRepository itemRepository;
Исполнил.

2023-10-21 10:02 UTC, SarychV commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    UserService userService;
Исполнил.

2023-10-21 10:09 UTC, SarychV commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public List<User> getAllUsers() {
Исполнил.

2023-10-21 10:39 UTC, SarychV commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    UserRepository userRepository;
Исполнил.

2023-10-21 11:43 UTC, SarychV commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User getUser(@PathVariable Integer userId) {
Исправил.

2023-10-21 11:43 UTC, SarychV commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User createUser(@RequestBody User user) {
Исправил.

2023-10-21 11:44 UTC, SarychV commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User updateUser(@RequestBody User user, @PathVariable Integer userId) {
Исправил.

2023-10-21 11:44 UTC, SarychV commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +public class UserMapper {
Исправил (заполнил класс).

2023-10-21 14:15 UTC, SarychV commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item createItem(@RequestHeader("X-Sharer-User-Id") @NotNull Integer ownerId,
Исполнил.

2023-10-21 14:16 UTC, SarychV commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public class ItemMapper {
Исполнил.

2023-10-21 14:18 UTC, SarychV commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
>  public class ItemRequest {
Это было в заготовке. Выше указано: TODO Sprint add-item-requests.

2023-10-22 14:13 UTC, ErkinKasymaliev approved these changes
привет, отличная работа!
оставил 1 коммент на ваше усмотрение - можете поправить перед мержем

2023-10-22 14:13 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public void hasValidEmailOrThrow() {
можно использовать готовую аннотацию @Email от Lombok над email

2023-10-22 14:27 UTC, SarychV commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public void hasValidEmailOrThrow() {
С ней не проходят тесты, так как проверка дает не тот код ошибки (дает 500, а надо 40x..).

2023-10-25 15:33 UTC, merged