Реализация требований TP14
SarychV/java-shareit pull request #2
Opened 2023-11-03 09:39 UTC by SarychV

2023-11-04 12:08 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-11-04 12:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestHeader("X-Sharer-User-Id") @NotNull Integer bookerId) {
"X-Sharer-User-Id" можно убрать в константу

2023-11-04 12:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +public class BookingServiceImpl {
BookingServiceImpl - Impl значит что вы имплементируете от какого интерфейса, его же я не вижу. Или добавьте интерфейс или уберите Impl из названия

2023-11-04 12:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam(required = false) String state) {
enum можно передавать в параметрах, State state. Spring поймет, и если будет передан неизвестный enum, то он кинет 400 ошибку

2023-11-04 12:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    protected StateStatus getStateStatus(final String state) {
этот метод не нужен, смотрите последний коммент в BookingController

2023-11-04 12:08 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestHeader("X-Sharer-User-Id") @NotNull Integer userId,
"X-Sharer-User-Id" лучше в константу убрать

2023-11-05 09:19 UTC, SarychV commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestHeader("X-Sharer-User-Id") @NotNull Integer bookerId) {
Исправил.

2023-11-05 09:19 UTC, SarychV commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestHeader("X-Sharer-User-Id") @NotNull Integer userId,
Исправил.

2023-11-05 09:21 UTC, SarychV commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +public class BookingServiceImpl {
Исправил (переименовал).

2023-11-05 09:54 UTC, SarychV commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    protected StateStatus getStateStatus(final String state) {
См. предпоследний комментарий.

2023-11-05 09:54 UTC, SarychV commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam(required = false) String state) {
Когда spring проверяет строку на соответствие enum, он возвращает ошибку 500. В тесте есть такое значение, но тест еще делает проверку на возврат строки:  pm.expect(jsonData.error, 'Error message').to.be.eql('Unknown state: UNSUPPORTED_STATUS'); 
Spring не может дать такой ответ, поэтому тест не пройдет.
Не вижу другого варианта, как проверять входящие значения с помощью метода и возвращать требуемое тестом значение. 
Поэтому оставил свой вариант, как есть.

2023-11-05 11:48 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-11-11 05:23 UTC, merged