Функциональность по требованиям ТЗ15
SarychV/java-shareit pull request #3
Opened 2023-11-17 15:15 UTC by SarychV

2023-11-18 07:29 UTC, ErkinKasymaliev requested changes
привет, все отлично, кроме одного момента, оставил коммент

2023-11-18 07:29 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        for (ItemRequest request : listSelection) {
вот здесь мне не совсем нравится, что если будет размер listSelection будет большим, даже 10 и получается что будет уходить 10 запросов, это нехорошо. Попробуйте сделать так чтобы отправлялся один запрос в бд

2023-11-20 09:06 UTC, SarychV commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        for (ItemRequest request : listSelection) {
Исправил.

2023-11-20 09:31 UTC, ErkinKasymaliev approved these changes
привет, работа принята!

2023-11-22 12:41 UTC, merged